const data = [
    {
        "id": 1,
        "category": "Remeras",
        "title": "Remera Blanca",
        "price": 200.99,
        "image": "https://media1.sistemacontinuo.com.ar/5289/remera-hombre-sublimable.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 2,
        "category": "Buzos",
        "title": "Buzo Gris",
        "price": 400.99,
        "image": "https://cdn.solodeportes.com.ar/media/catalog/product/cache/7c4f9b393f0b8cb75f2b74fe5e9e52aa/b/u/buzo-con-capucha-puma-classics-oversized-mujer-celeste-640020530412061-1.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 3,
        "category": "Abrigos",
        "title": "Campera",
        "price": 200.99,
        "image": "https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw9cb7a555/BH5388_031_24.jpg?imwidth=915&impolicy=product",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 4,
        "category": "Abrigos",
        "title": "Bufanda",
        "price": 200.99,
        "image": "https://www.corbataslester.com/magazine/wp-content/uploads/2018/10/bufanda-03.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 5,
        "category": "Remeras",
        "title": "Remera Roja",
        "price": 208.99,
        "image": "https://media.istockphoto.com/photos/red-tshirt-mockup-men-as-design-template-tee-shirt-blank-isolated-on-picture-id1354031012?k=20&m=1354031012&s=612x612&w=0&h=wG3hVNaaoDTDEFpb3Ad-O7cJribxbNXXNCcjHJTrJH8=",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 6,
        "category": "Buzos",
        "title": "Buzo Verde",
        "price": 450.99,
        "image": "http://d2r9epyceweg5n.cloudfront.net/stores/001/458/807/products/bz-crs-verde_ingles-5b92cb013a8269f66216141306343837-640-0.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 7,
        "category": "Abrigos",
        "title": "Gorro Lana",
        "price": 56.99,
        "image": "https://images.ecestaticos.com/VKUb7lX3LCHWtAgrxfYh9TbKeiY=/12x26:617x812/1440x1920/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fdea%2F4d8%2F413%2Fdea4d84135e21a94b8b1bf47c1b932d6.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
    {
        "id": 8,
        "category": "Remeras",
        "title": "Remera Azul",
        "price": 160.99,
        "image": "https://st3.depositphotos.com/1226172/19368/i/450/depositphotos_193689568-stock-photo-navy-blue-plain-shortsleeve-cotton.jpg",
        "description": "A product description is the marketing copy that explains what a product is and why it's worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so they're compelled to buy.",
        "stock": 10,
    },
]

export default data;